name: Waka Readme
on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'
jobs:
  update-readme:
    name: WakaTime Stats Charts Generator    
    runs-on: ubuntu-latest
    steps:
        - uses: dvjn/wakatime-charts@v0.3.1
          with:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            SHOW_TITLE: true
            TIME_RANGE: all_time
            SHOW_TIME: true
            SHOW_MASKED_TIME: true
          
          
    
